site_name: MDI Wiki
site_author: NiTiS-Dev
site_description: Official Wiki of MoreDumbItems mod
site_url: https://nitis-dev.github.io/mdi-wiki/
repo_url: https://github.com/NiTiS-Dev/mdi-wiki
edit_url: ""
docs_dir: 'docs'
theme: 
  name: material
  favicon: images/favicon.png
  logo: images/favicon.png
  custom_dir: overrides
  shortcuts:
    help: 191    # ?
    next: 39     # right arrow
    previous: 37 # left arrow
    search: 83   # s
  features:
    - navigation.tracking
extra_css:
  - 'stylesheets/style.css'
